[metadata]
name = CreateTestFile
version = 0.0.1
description = CreateTestFile package description
author = Tools
long_description = file: README.md
keywords = Tools, Assistant, Python, Revit

[options]
packages = CreateTestFile
install_requires =
    cwpy

[options.package_data]
* = Icon.png
* = Help.md

[options.entry_points]
assistant_scripts =
    main = CreateTestFile