<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <Title>Assistant Demo Extension</Title>
    <Description>AssistantDemoExtension Description</Description>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="CW.Assistant.Extensions.Assistant" Version="26.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>

