<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ExtensionId>OpenWorksets</ExtensionId>
    <Authors>AEC AB</Authors>
    <Version>1.1.0</Version>
    <Title>Open Worksets</Title>
    <Description>Open closed worksets in Revit models using direct selection or regular expression matching. Reloads the linked models that live in those worksets and reports workset and link status.</Description>
    <PackageTags>Revit;Assistant;Extension;Automation</PackageTags>
    <PackageIcon>Icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Icon.png" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
